name: publish
on:
  push:
    branches:
      - 'main'
      - 'next'
      - 'beta'
  pull_request:
jobs:
  publish-module:
    name: 'Publish Module to NPM'
    if: github.repository == 'tannerlinsley/react-location' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta' || github.ref == 'refs/heads/next')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - run: |
          git config --global user.name 'Tanner Linsley'
          git config --global user.email 'tannerlinsley@users.noreply.github.com'
          yarn cipublish
        env:
          YARN_REGISTRY: https://registry.npmjs.org/
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          # GH_TOKEN: ${{secrets.GH_TOKEN}}
